### ISSUE TITLE
buttons not appering, Mac OS

### ISSUE THREAD

**Issue by Tiago-udi** [BaldrAI/OpenOTDR#24]
I was trying to figure out how to use this software, after i compile it in my mac computer. I just realize the buttons are not appearing, and i started clicking upwards and discovered some buttons on upper left side. 
Image follows:
![Captura de Tela 2024-07-23 às 15 13 38](https://github.com/user-attachments/assets/3e740a5e-27c0-4faa-b4ea-5756ec2cf600)

**Comment by hydratim** [comment]
Hey, @Tiago-udi Thanks for taking the time to test it. Yes, this is a known bug with the old python version.

As we mentioned in the recently updated Readme, we've been working really hard on a complete rewrite in C#, which we'll be releasing a Beta of over the next week or so.

I'll update you here in this thread when it's available.

**Comment by hydratim** [comment]
Hi @Tiago-udi,

We've just released v.1.0.0-alpha1 of OpenOTDR, you can read about this release here: https://github.com/BaldrAI/OpenOTDR/releases/tag/1.0.0-alpha1

Please let us know about any bugs, issues, or feedback you have!
